version: '3.8'

services:
    # Vue App.
    app-builder:
        image: app-builder-image:${TAG:-latest}
        build:
            context: .
            dockerfile: docker/Dockerfile.local
            target: builder

    # LOCAL Service
    caddy-local:
        image: caddy:2.10.0-alpine
        profiles:
            - local
        container_name: web_caddy_local
        ports:
            - "8080:80"
        volumes:
            - ./dist:/usr/share/caddy
            - ./caddy/WebCaddyfile.local:/etc/caddy/Caddyfile

    # PRODUCTION Service
    caddy-prod:
        profiles:
            - prod
        container_name: web_caddy_prod
        image: web-prod-builder:${TAG:-latest}
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile.prod
            args:
                # Updated image name argument
                BUILDER_IMAGE: app-builder-image:${TAG:-latest}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - oullin_web_data:/data
            - oullin_web_config:/config
        depends_on:
            - app-builder

volumes:
    oullin_web_data:
    oullin_web_config:
