services:
    app-builder:
        env_file:
            - ./.env
        profiles:
            - builder # Prevent the app-builder service from starting during your production deployment
        image: app-builder-image:${TAG:-latest}
        container_name: app-builder
        build:
            args:
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
            context: .
            dockerfile: docker/Dockerfile
            target: builder
        networks:
            - web_internal

    caddy-prod:
        env_file:
            - ./.env
        profiles:
            - prod
        container_name: web_caddy_prod
        image: web-prod-builder:${TAG:-latest}
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
                BUILDER_IMAGE: app-builder-image:${TAG:-latest}
        volumes:
            - oullin_web_data:/data
            - oullin_web_config:/config
            - ./caddy/mtls:/etc/caddy/mtls:ro
            - ./public/seo:/usr/share/caddy/seo:ro
            - ./public/images:/usr/share/caddy/images:ro
            - ./public/images/seo:/usr/share/caddy/images/seo:ro
        networks:
            caddy_net:
                aliases:
                    - web

    caddy-local:
        image: caddy:2.10.2-alpine
        profiles:
            - local
        container_name: web_caddy_local
        ports:
            - "5173:80"
        environment:
            - RELAY_UPSTREAM=http://host.docker.internal:8080
        volumes:
            - ./dist:/usr/share/caddy:ro
            - ./caddy/mtls:/etc/caddy/mtls:ro
            - ./public/seo:/usr/share/caddy/seo:ro
            - ./public/images:/usr/share/caddy/images:ro
            - ./caddy/WebCaddyfile.local:/etc/caddy/Caddyfile
        networks:
            - web_internal
        extra_hosts:
            - "host.docker.internal:host-gateway"

    caddy-watcher:
        working_dir: /app
        image: node:22.9.0-alpine3.19
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
            - .:/app
        profiles:
            - local
        depends_on:
            - caddy-local
        command: >
            sh -lc "
              npm ci &&
              mkdir -p dist &&
              npm run build -- --watch --emptyOutDir=false
            "

networks:
    web_internal:
        driver: bridge
    caddy_net:
        external: true

volumes:
    oullin_web_data:
    oullin_web_config:
