services:
    # Vue App.
    app-builder:
        env_file:
            - ./.env
        profiles:
            - builder # Prevent the app-builder service from starting during your production deployment
        image: app-builder-image:${TAG:-latest}
        container_name: app-builder
        build:
            args:
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
            context: .
            dockerfile: docker/Dockerfile
            target: builder
        networks:
            - web_internal

    # LOCAL Service
    caddy-local:
        image: caddy:2.10.0-alpine
        profiles:
            - local
        container_name: web_caddy_local
        ports:
            - "5173:80"
        volumes:
            - ./dist:/usr/share/caddy
            - ./caddy/WebCaddyfile.internal:/etc/caddy/Caddyfile
            - ./caddy/mtls:/etc/caddy/mtls:ro
            - ./public/seo:/usr/share/caddy/seo:ro
        networks:
            - web_internal

    # PRODUCTION Service
    caddy-prod:
        env_file:
            - ./.env
        profiles:
            - prod
        container_name: web_caddy_prod
        image: web-prod-builder:${TAG:-latest}
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                BUILDER_IMAGE: app-builder-image:${TAG:-latest}
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
        volumes:
            - oullin_web_data:/data
            - oullin_web_config:/config
            - ./caddy/mtls:/etc/caddy/mtls:ro
            - ./public/seo:/usr/share/caddy/seo:ro
        networks:
            caddy_net:
                aliases:
                    - web

networks:
    web_internal:
        driver: bridge
    caddy_net:
        external: true

volumes:
    oullin_web_data:
    oullin_web_config:
