services:
    # --- SPA BUILDER ---
    #     Builds the SPA and places it in the /dist folder.
    app-builder:
        env_file:
            - ./.env
        profiles:
            - builder # Prevent the app-builder service from starting during your production deployment
        image: app-builder-image:${TAG:-latest}
        container_name: app-builder
        build:
            args:
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
            context: .
            dockerfile: docker/Dockerfile
            target: builder
        networks:
            - web_internal

    # --- SPA's PRODUCTION NODE SERVER SERVICES FOR SSR ---
    app-server:
        env_file:
            - ./.env
        profiles:
            - prod
        container_name: oullin-app-server
        image: app-builder-image:${TAG:-latest}
        restart: unless-stopped
        build:
            args:
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
            context: .
            dockerfile: docker/Dockerfile
        environment:
            - NODE_ENV=production
        depends_on:
            - app-builder
        networks:
            caddy_net:
                aliases:
                    - web

    # --- LOCAL DEVELOPMENT SERVICES ---
    #     Runs the Vite dev server with hot-reloading
    app-local:
        profiles:
            - local
        container_name: oullin-app-local
        build:
            context: .
            dockerfile: docker/Dockerfile.local
            args:
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules # Exclude node_modules from the mount
        env_file:
            - ./.env
        environment:
            - NODE_ENV=development
        networks:
            - web_internal

    # --- CADDY LOCAL ---
    #     Caddy reverse proxy for local development
    caddy-local:
        image: caddy:2.10.0-alpine
        profiles:
            - local
        container_name: web_caddy_local
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile.local
            args:
                BUILDER_IMAGE: app-builder-image:${TAG:-latest}
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
        ports:
            - "8080:80"
        volumes:
            - ./caddy/Caddyfile.local:/etc/caddy/Caddyfile
        networks:
            - web_internal
        depends_on:
            - app-local

    # --- CADDY PRODUCTION ---
    #     Caddy reverse proxy for production environments.
    caddy-prod:
        env_file:
            - ./.env
        profiles:
            - prod
        container_name: web_caddy_prod
        image: web-prod-builder:${TAG:-latest}
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                BUILDER_IMAGE: app-builder-image:${TAG:-latest}
                VITE_API_ENV: ${VITE_API_ENV}
                VITE_API_URL: ${VITE_API_URL}
                VITE_HOST_URL: ${VITE_HOST_URL}
                VITE_ACCOUNT_NAME: ${VITE_ACCOUNT_NAME}
                VITE_PUBLIC_KEY: ${VITE_PUBLIC_KEY}
                ENV_API_LOCAL_DIR: ${ENV_API_LOCAL_DIR}
        volumes:
            - oullin_web_data:/data
            - oullin_web_config:/config
            - ./caddy/mtls:/etc/caddy/mtls:ro
        networks:
            caddy_net:
                aliases:
                    - web

networks:
    web_internal:
        driver: bridge
    caddy_net:
        external: true

volumes:
    oullin_web_data:
    oullin_web_config:
