# --- Builder
ARG BUILDER_IMAGE=app-builder-image:latest
FROM ${BUILDER_IMAGE} AS builder

# --- Artifact
FROM caddy:2.10.0-alpine
COPY --from=builder /app/dist /usr/share/caddy

# Makes caddy work as an internal static web server.
COPY caddy/WebCaddyfile.internal /etc/caddy/Caddyfile
