title: Gus SPA
properties:
    have_fun: false
    code_review:
        disable: false
        comment_severity_threshold: CRITICAL
        max_review_comments: -1
        pull_request_opened:
            help: false
            summary: true
            code_review: false
            include_drafts: true
    ignore_patterns: []
