name: Test Format Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  format-check:
    if: contains(github.event.pull_request.labels.*.name, 'testing')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm install --no-package-lock

      - run: make format

      - run: git diff --exit-code
